// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCYmDA5lC9zHbTqq7FrH-KZZigMH_dMto',
    appId: '1:318299286189:web:0fdd5ed4b9df1b6a473424',
    messagingSenderId: '318299286189',
    projectId: 'point-draw-web-app',
    authDomain: 'point-draw-web-app.firebaseapp.com',
    databaseURL: 'https://point-draw-web-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'point-draw-web-app.appspot.com',
    measurementId: 'G-P9SFLJVX2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM2PeETuIjGdE31-eOwT10ULtHcsZLd44',
    appId: '1:318299286189:android:8cb341de61f4855e473424',
    messagingSenderId: '318299286189',
    projectId: 'point-draw-web-app',
    databaseURL: 'https://point-draw-web-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'point-draw-web-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ9cXLBMwxi_ykwxqTIRGlLwXH4nTyQ3Q',
    appId: '1:318299286189:ios:f0e8b188c9355731473424',
    messagingSenderId: '318299286189',
    projectId: 'point-draw-web-app',
    databaseURL: 'https://point-draw-web-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'point-draw-web-app.appspot.com',
    iosClientId: '318299286189-b447fandeh0826g08vghpidhfei7k2ke.apps.googleusercontent.com',
    iosBundleId: 'com.kopico.pointdraw',
  );
}
